services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/card-embosser.nginx.conf:/etc/nginx/conf.d/card-embosser.nginx.conf
      - ./cert:/etc/nginx/certs
    depends_on:
      - frontend
    
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    command: npm run start:dev
    depends_on:
      - db
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules

  db:
    image: mongodb/mongodb-community-server:7.0.9-ubuntu2204
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/data:/data/db
