services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/card-embosser.nginx.conf:/etc/nginx/conf.d/card-embosser.nginx.conf
      - ./cert:/etc/nginx/certs
    depends_on:
      - frontend
    
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    command: npm run start:dev
    # environment:
    #   - DB_HOST=db
    # depends_on:
    #   - db
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=appdb
  #     - POSTGRES_USER=appuser
  #     - POSTGRES_PASSWORD=apppass
